on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      CC: gcc
    steps:
    - run: |
        sudo apt-get update && sudo apt-get install \
          autotools-dev \
          libatasmart-dev \
          libcap-dev \
          libcurl4-gnutls-dev \
          libdbi0-dev \
          libesmtp-dev \
          libganglia1-dev \
          libgcrypt20-dev \
          libglib2.0-dev \
          libgps-dev \
          libhiredis-dev \
          libi2c-dev \
          libiptc-dev \
          libldap2-dev \
          libltdl-dev \
          liblua50-dev \
          liblua5.1-0-dev \
          liblua5.2-dev \
          libmemcached-dev \
          libmicrohttpd-dev \
          libmnl-dev \
          libmodbus-dev \
          libmongoc-dev \
          libmosquitto-dev \
          libmysqlclient-dev \
          libnotify-dev \
          libopenipmi-dev \
          liboping-dev \
          libow-dev \
          libpcap-dev \
          libperl-dev \
          libpq-dev \
          libprotobuf-c-dev \
          librabbitmq-dev \
          librdkafka-dev \
          libriemann-client-dev \
          librrd-dev \
          libsensors4-dev \
          libsigrok-dev \
          libsnmp-dev \
          libtokyocabinet-dev \
          libtokyotyrant-dev \
          libudev-dev \
          libupsclient-dev \
          libvarnish-dev \
          libvirt-dev \
          libxen-dev \
          libxml2-dev \
          libxtables-dev \
          libyajl-dev \
          linux-libc-dev \
          perl \
          protobuf-c-compiler \
          python3-dev \
          python-dev \
          xfslibs-dev
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: autoconf
      run: |
        sh clean.sh
        sh build.sh
        autoreconf -vif
    - run: ./configure --enable-debug
    # VERBOSE=1 dumps the contents of the test suites logs to standard output.
    # -fsanitize=address enables https://github.com/google/sanitizers/wiki/AddressSanitizer
    # -ldl works around a dlsym error when tsan is enabled in this environment.
    - run: make check VERBOSE=1 CFLAGS=-fsanitize=address LDFLAGS="-ldl -fsanitize=address"
    - run: make distcheck
